services:
  archivist-node1:
    image: archivist:latest
    environment:
      - ARCHIVIST_LOG_LEVEL=${ARCHIVIST_LOG_LEVEL:-TRACE}
      - ARCHIVIST_METRICS=${ARCHIVIST_METRICS:-false}
      - ARCHIVIST_METRICS_ADDRESS=${ARCHIVIST_METRICS_ADDRESS:-0.0.0.0}
      - ARCHIVIST_METRICS_PORT=${ARCHIVIST_METRICS_PORT:-8008}
      - ARCHIVIST_DATA_DIR=${ARCHIVIST_DATA_DIR:-/datadir}
      - ARCHIVIST_LISTEN_ADDRS=${ARCHIVIST_LISTEN_ADDRS:-/ip4/0.0.0.0/tcp/2345}
      - ARCHIVIST_NAT=${ARCHIVIST_NAT:-10.0.0.10}
      - ARCHIVIST_DISC_PORT=${ARCHIVIST_DISC_PORT:-8090}
      - ARCHIVIST_NET_PRIVKEY=${ARCHIVIST_NET_PRIVKEY:-key}
      # - ARCHIVIST_BOOTSTRAP_NODE=${ARCHIVIST_BOOTSTRAP_NODE}
      - ARCHIVIST_MAX_PEERS=${ARCHIVIST_MAX_PEERS:-160}
      - ARCHIVIST_AGENT_STRING=${ARCHIVIST_AGENT_STRING:-Archivist}
      - ARCHIVIST_API_BINDADDR=${ARCHIVIST_API_BINDADDR:-0.0.0.0}
      - ARCHIVIST_API_PORT=${ARCHIVIST_API_PORT:-8080}
      - ARCHIVIST_REPO_KIND=${ARCHIVIST_REPO_KIND:-fs}
      - ARCHIVIST_STORAGE_QUOTA=${ARCHIVIST_STORAGE_QUOTA:-8589934592}
      - ARCHIVIST_BLOCK_TTL=${ARCHIVIST_BLOCK_TTL:-0}
      # - ARCHIVIST_BLOCK_MI=${ARCHIVIST_BLOCK_MI}
      - ARCHIVIST_BLOCK_MN=${ARCHIVIST_BLOCK_MN:-1000}
      - ARCHIVIST_CACHE_SIZE=${ARCHIVIST_CACHE_SIZE:-0}
      - ARCHIVIST_PERSISTENCE=${ARCHIVIST_PERSISTENCE:-false}
      - ARCHIVIST_ETH_PROVIDER=${ARCHIVIST_ETH_PROVIDER:-ws://localhost:8545}
      # - ARCHIVIST_ETH_ACCOUNT=${ARCHIVIST_ETH_ACCOUNT}
      # - ARCHIVIST_MARKETPLACE_ADDRESS=${ARCHIVIST_MARKETPLACE_ADDRESS:-0x59b670e9fA9D0A427751Af201D676719a970857b}
      - ARCHIVIST_VALIDATOR=${ARCHIVIST_VALIDATOR:-false}
      - ARCHIVIST_VALIDATOR_MAX_SLOTS=${ARCHIVIST_VALIDATOR_MAX_SLOTS:-1000}
      - NAT_IP_AUTO=false
      - NAT_PUBLIC_IP_AUTO=https://ipinfo.io/ip
    ports:
      - 8080:8080/tcp # REST API
      - 8008:8008/tcp # Metrics
      - 2345:2345/tcp # libp2p
      - 8090:8090/udp # DHT discovery
    volumes:
      - ./datadir:/datadir:z
    networks:
      - archivist
networks:
  archivist:
    driver: bridge
