name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  cache_nonce: 0 # Allows for easily busting actions/cache caches
  nim_version: v2.2.4

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
      cache_nonce: ${{ env.cache_nonce }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Compute matrix
        id: matrix
        run: |
          echo 'matrix<<EOF' >> $GITHUB_OUTPUT
          tools/scripts/ci-job-matrix.sh >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

  build:
    needs: matrix
    uses: ./.github/workflows/ci-reusable.yml
    with:
      matrix: ${{ needs.matrix.outputs.matrix }}
      cache_nonce: ${{ needs.matrix.outputs.cache_nonce }}

  linting:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Check `nph` formatting
        uses: arnetheduck/nph-action@v1
        with:
          version: 0.6.1
          options: "archivist/ tests/"
          fail: true
          suggest: true
