{
 "title": "Archivist node",
 "tags": [ "archivist" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(process_virtual_memory_bytes,node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values({node=~\"$node\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values({namespace=~\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Archivist Inflight Discovery",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "archivistInflightDiscovery{}", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node)(irate(node_cpu_seconds_total{mode=\"system\",node=~\"$node\",}[5m])) * 100",
     "legendFormat": "Busy System - {{node}}"
    },
    {
     "expr": "sum by (node)(irate(node_cpu_seconds_total{mode='user',node=~\"$node\"}[5m])) * 100",
     "legendFormat": "Busy User - {{node}}"
    },
    {
     "expr": "sum by (node)(irate(node_cpu_seconds_total{mode='iowait',node=~\"$node\"}[5m])) * 100",
     "legendFormat": "Busy Iowait - {{node}}"
    },
    {
     "expr": "sum by (node)(irate(node_cpu_seconds_total{mode=~\".*irq\",node=~\"$node\"}[5m])) * 100",
     "legendFormat": "Busy IRQs - {{node}}"
    },
    {
     "expr": "sum by (node)(irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',node=~\"$node\",}[5m])) * 100",
     "legendFormat": "Busy Other - {{node}}"
    },
    {
     "expr": "sum by (node)(irate(node_cpu_seconds_total{mode='idle',node=~\"$node\"}[5m])) * 100",
     "legendFormat": "Idle - {{node}}"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"$node\"}",
     "legendFormat": "RAM Total - {{node}}"
    },
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"$node\"} - node_memory_MemFree_bytes{node=~\"$node\"} - (node_memory_Cached_bytes{node=~\"$node\"} + node_memory_Buffers_bytes{node=~\"$node\"})",
     "legendFormat": "RAM Used - {{node}}"
    },
    {
     "expr": "node_memory_Cached_bytes{node=~\"$node\"} + node_memory_Buffers_bytes{node=~\"$node\"}",
     "legendFormat": "RAM Cache + Buffer - {{node}}"
    },
    {
     "expr": "node_memory_MemFree_bytes{node=~\"$node\"}",
     "legendFormat": "RAM Free - {{node}}"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{node=~\"$node\"} - node_memory_SwapFree_bytes{node=~\"$node\"})",
     "legendFormat": "SWAP Used - {{node}}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{node=~\"$node\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{node=~\"$node\"}[5m])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Resources - $node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nim_gc_mem_occupied_bytes{node=~\"$node\"}",
     "legendFormat": "Nim GC mem used - {{node}}"
    }
   ]
  },
  {
   "title": "GC heap objects - $pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nim_gc_heap_instance_occupied_bytes{node=~\"${node}\",namespace=~\"${namespace}\",pod=~\"$pod\"}",
     "legendFormat": "{{type_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Chronos Profiler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cumulative Chronos Thread Occupancy (exec time)",
     "type": "timeseries",
     "description": "Shows the time each future (async proc) spent occupying the Chronos thread.",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 231 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "chronos_exec_time_with_children_total{node=~\"${node}\",namespace=~\"${namespace}\",pod=~\"$pod\"}",
       "legendFormat": "{{proc}} [{{file}}:{{line}}]"
      }
     ]
    },
    {
     "title": "Chronos Thread Occupancy (60s increase)",
     "type": "timeseries",
     "description": "Shows the time each future (async proc) spent occupying the Chronos thread over a 60 second rolling window.",
     "gridPos": { "h": 17, "w": 12, "x": 12, "y": 231 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "increase(chronos_exec_time_with_children_total{node=~\"${node}\",namespace=~\"${namespace}\",pod=~\"$pod\"}[60s])",
       "legendFormat": "{{proc}} [{{file}}:{{line}}]"
      }
     ]
    },
    {
     "title": "Max Chronos Thread Occupancy Time",
     "type": "timeseries",
     "description": "The maximum time taken by a single call of an async proc. Does not take into account calls that have not yet completed.",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 305 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "chronos_single_exec_time_max{node=~\"${node}\",namespace=~\"${namespace}\",pod=~\"$pod\"}",
       "legendFormat": "{{proc}} [{{file}}:{{line}}]"
      }
     ]
    },
    {
     "title": "Call Count (60s increase)",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 305 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(chronos_call_count_total{node=~\"${node}\",namespace=~\"${namespace}\",pod=~\"$pod\"}[60s])",
       "legendFormat": "{{proc}} [{{file}}:{{line}}]"
      }
     ]
    },
    {
     "title": "Cumulative Call Count (Total)",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 319 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "chronos_call_count_total{node=~\"${node}\",namespace=~\"${namespace}\",pod=~\"$pod\"}",
       "legendFormat": "{{proc}} [{{file}}:{{line}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Archivist - API Upload/Download",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uploads - $pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 309 },
     "targets": [
      {
       "expr": "sum by (pod) (archivist_api_uploads_total{node=~\"$node\",namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Downloads - $pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 318 },
     "targets": [
      {
       "expr": "sum by (pod) (archivist_api_downloads_total{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Archivist - Network Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "libp2p peers - $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(pod) (libp2p_peers{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "connected peers - {{pod}}"
      },
      {
       "expr": "sum by (pod) (libp2p_pubsub_peers{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "pubsub peers - {{pod}}"
      }
     ]
    },
    {
     "title": "libp2p open streams - $pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(type, dir, pod) (libp2p_open_streams{node=~\"$node\",namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "{{type}} , {{dir}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Discovery Requests rate - $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
     "targets": [
      {
       "expr": "rate(sum by (pod) (dht_message_requests_incoming_total{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"}))",
       "legendFormat": "-> {{ pod }}"
      },
      {
       "expr": "- sum by (pod) (discovery_message_requests_outgoing_total{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "<- {{ pod }}"
      }
     ]
    },
    {
     "title": "Discovery LRU - $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 103 },
     "targets": [
      {
       "expr": "rate(sum by (pod) (dht_session_lru_cache_hits_total{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"}))",
       "legendFormat": "hits - {{ pod }}"
      },
      {
       "expr": "- sum by (pod) (discovery_session_lru_cache_misses_total{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "misses - {{ pod }}"
      }
     ]
    },
    {
     "title": "DHT: Routing table nodes - $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 111 },
     "targets": [
      {
       "expr": "sum by (pod) (dht_routing_table_nodes {state=\"\", node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Archivist - Block Exchange",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blocks sent - $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 371 },
     "targets": [
      {
       "expr": "sum by(pod) (archivist_block_exchange_blocks_sent_total{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Blocks sent (60s increase)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 371 },
     "targets": [
      {
       "expr": "increase(archivist_block_exchange_blocks_sent_total{node=~\"${node}\",namespace=~\"${namespace}\",pod=~\"$pod\"}[60s])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "WantHave lists sent - $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 379 },
     "targets": [
      {
       "expr": "sum by(pod) (archivist_block_exchange_want_have_lists_sent_total{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "WantHave lists sent - $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 379 },
     "targets": [
      {
       "expr": "increase(archivist_block_exchange_want_have_lists_sent_total{node=~\"${node}\",namespace=~\"${namespace}\",pod=~\"$pod\"}[60s])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "WantBlock lists sent - $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 387 },
     "targets": [
      {
       "expr": "sum by(pod) (archivist_block_exchange_want_block_lists_sent_total{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "WantBlock lists sent - $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 387 },
     "targets": [
      {
       "expr": "increase(archivist_block_exchange_want_block_lists_sent_total{node=~\"${node}\",namespace=~\"${namespace}\",pod=~\"$pod\"}[60s])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "WantHave lists received - $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 395 },
     "targets": [
      {
       "expr": "sum by(pod) (archivist_block_exchange_want_have_lists_received_total{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "WantBlock lists received - $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 395 },
     "targets": [
      {
       "expr": "sum by(pod) (archivist_block_exchange_want_block_lists_received_total{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Archivist - Local Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Blocks - $pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 370 },
     "targets": [
      {
       "expr": "sum by(pod) (archivist_repostore_blocks{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Bytes used - $pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 379 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(pod) (archivist_repostore_bytes_used{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Bytes reserved - $pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 388 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(pod) (archivist_repostore_bytes_reserved{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Archivist - KVStore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "KVStore API Retries - rate/s",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(kvstore_tryput_retries_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "tryPut retries"
      },
      {
       "expr": "rate(kvstore_tryputatomic_retries_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "tryPutAtomic retries"
      },
      {
       "expr": "rate(kvstore_trydelete_retries_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "tryDelete retries"
      },
      {
       "expr": "rate(kvstore_trydeleteatomic_retries_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "tryDeleteAtomic retries"
      }
     ]
    },
    {
     "title": "KVStore API Exhausted Retries - rate/s",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(kvstore_tryput_exhausted_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "tryPut exhausted"
      },
      {
       "expr": "rate(kvstore_tryputatomic_exhausted_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "tryPutAtomic exhausted"
      },
      {
       "expr": "rate(kvstore_trydelete_exhausted_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "tryDelete exhausted"
      },
      {
       "expr": "rate(kvstore_trydeleteatomic_exhausted_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "tryDeleteAtomic exhausted"
      }
     ]
    },
    {
     "title": "SQL Operations - rate/s",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(kvstore_sql_put_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "put"
      },
      {
       "expr": "rate(kvstore_sql_get_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "get"
      },
      {
       "expr": "rate(kvstore_sql_has_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "has"
      },
      {
       "expr": "rate(kvstore_sql_delete_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "delete"
      },
      {
       "expr": "rate(kvstore_sql_putatomic_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "putAtomic"
      },
      {
       "expr": "rate(kvstore_sql_deleteatomic_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "deleteAtomic"
      },
      {
       "expr": "rate(kvstore_sql_move_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "moveKeys"
      },
      {
       "expr": "rate(kvstore_sql_query_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "query"
      }
     ]
    },
    {
     "title": "SQL CAS Conflicts - rate/s",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(kvstore_sql_put_conflict_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "put conflicts"
      },
      {
       "expr": "rate(kvstore_sql_delete_conflict_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "delete conflicts"
      },
      {
       "expr": "rate(kvstore_sql_putatomic_conflict_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "putAtomic conflicts"
      },
      {
       "expr": "rate(kvstore_sql_putatomic_rollback_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "putAtomic rollbacks"
      },
      {
       "expr": "rate(kvstore_sql_deleteatomic_conflict_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "deleteAtomic conflicts"
      },
      {
       "expr": "rate(kvstore_sql_deleteatomic_rollback_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "deleteAtomic rollbacks"
      },
      {
       "expr": "rate(kvstore_sql_moveatomic_error_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "moveAtomic errors"
      }
     ]
    },
    {
     "title": "SQL Duration p50/p95/p99 - put",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(kvstore_sql_put_duration_seconds_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kvstore_sql_put_duration_seconds_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kvstore_sql_put_duration_seconds_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "SQL Duration p50/p95/p99 - get",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(kvstore_sql_get_duration_seconds_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kvstore_sql_get_duration_seconds_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kvstore_sql_get_duration_seconds_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "SQL Duration p50/p95/p99 - putAtomic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(kvstore_sql_putatomic_duration_seconds_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kvstore_sql_putatomic_duration_seconds_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kvstore_sql_putatomic_duration_seconds_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "SQL Duration p50/p95/p99 - moveKeys",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(kvstore_sql_move_duration_seconds_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kvstore_sql_move_duration_seconds_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kvstore_sql_move_duration_seconds_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "SQL Batch Sizes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(kvstore_sql_put_batch_size_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "put p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kvstore_sql_put_batch_size_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "put p95"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(kvstore_sql_putatomic_batch_size_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "putAtomic p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kvstore_sql_putatomic_batch_size_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "putAtomic p95"
      }
     ]
    },
    {
     "title": "SQL In-Flight Operations",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kvstore_sql_inflight_put{namespace=~\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "put"
      },
      {
       "expr": "kvstore_sql_inflight_get{namespace=~\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "get"
      },
      {
       "expr": "kvstore_sql_inflight_has{namespace=~\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "has"
      },
      {
       "expr": "kvstore_sql_inflight_delete{namespace=~\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "delete"
      },
      {
       "expr": "kvstore_sql_inflight_putatomic{namespace=~\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "putAtomic"
      },
      {
       "expr": "kvstore_sql_inflight_deleteatomic{namespace=~\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "deleteAtomic"
      }
     ]
    },
    {
     "title": "SQL Value Sizes p50/p95",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(kvstore_sql_put_value_bytes_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "put p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kvstore_sql_put_value_bytes_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "put p95"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(kvstore_sql_get_value_bytes_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "get p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kvstore_sql_get_value_bytes_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "get p95"
      }
     ]
    },
    {
     "title": "SQL Active Iterators",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kvstore_sql_active_iterators{namespace=~\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "iterators"
      }
     ]
    },
    {
     "title": "FS Operations - rate/s",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(kvstore_fs_put_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "put"
      },
      {
       "expr": "rate(kvstore_fs_get_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "get"
      },
      {
       "expr": "rate(kvstore_fs_has_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "has"
      },
      {
       "expr": "rate(kvstore_fs_delete_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "delete"
      },
      {
       "expr": "rate(kvstore_fs_query_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "query"
      }
     ]
    },
    {
     "title": "FS CAS Conflicts - rate/s",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(kvstore_fs_put_conflict_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "put conflicts"
      },
      {
       "expr": "rate(kvstore_fs_delete_conflict_total_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
       "legendFormat": "delete conflicts"
      }
     ]
    },
    {
     "title": "FS Duration p50/p95/p99 - put",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(kvstore_fs_put_duration_seconds_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kvstore_fs_put_duration_seconds_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kvstore_fs_put_duration_seconds_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "FS Duration p50/p95/p99 - get",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(kvstore_fs_get_duration_seconds_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kvstore_fs_get_duration_seconds_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kvstore_fs_get_duration_seconds_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "FS Batch Sizes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(kvstore_fs_put_batch_size_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "put p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kvstore_fs_put_batch_size_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "put p95"
      }
     ]
    },
    {
     "title": "FS In-Flight Operations",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kvstore_fs_inflight_put{namespace=~\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "put"
      },
      {
       "expr": "kvstore_fs_inflight_get{namespace=~\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "get"
      },
      {
       "expr": "kvstore_fs_inflight_has{namespace=~\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "has"
      },
      {
       "expr": "kvstore_fs_inflight_delete{namespace=~\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "delete"
      }
     ]
    },
    {
     "title": "FS Value Sizes p50/p95",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(kvstore_fs_put_value_bytes_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "put p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kvstore_fs_put_value_bytes_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "put p95"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(kvstore_fs_get_value_bytes_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "get p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kvstore_fs_get_value_bytes_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (le, pod))",
       "legendFormat": "get p95"
      }
     ]
    },
    {
     "title": "FS Active Iterators",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kvstore_fs_active_iterators{namespace=~\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "iterators"
      }
     ]
    }
   ]
  },
  {
   "title": "Archivist - Purchases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pending - $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 187 },
     "targets": [
      {
       "expr": "sum by(pod) (archivist_purchases_pending_total{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Submitted - $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 187 },
     "targets": [
      {
       "expr": "sum by(pod) (archivist_purchases_submitted_total{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Started - $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 187 },
     "targets": [
      {
       "expr": "sum by(pod) (archivist_purchases_started_total{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Finished - $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 187 },
     "targets": [
      {
       "expr": "sum by(pod) (archivist_purchases_finished_total{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Failed - $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 195 },
     "targets": [
      {
       "expr": "sum by(pod) (archivist_purchases_failed_total{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Cancelled - $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 195 },
     "targets": [
      {
       "expr": "sum by(pod) (archivist_purchases_cancelled_total{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Unknown - $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 195 },
     "targets": [
      {
       "expr": "sum by(pod) (archivist_purchases_unknown_total{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Error - $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 195 },
     "targets": [
      {
       "expr": "sum by(pod) (archivist_purchases_error_total{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Archivist - Proofs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Proofs per period - $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 188 },
     "targets": [
      {
       "expr": "sum by(pod) (archivist_proofs_per_period{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage - $pod ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 220 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m]))",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Processes - $pod ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 227 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(pod) (container_processes{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",image!=\"\",container!~\"POD|\"})",
       "legendFormat": "Processes - {{ pod }}"
      },
      {
       "expr": "sum by(pod) (container_threads{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",image!=\"\",container!~\"POD|\"})",
       "legendFormat": "Threads - {{ pod }}"
      },
      {
       "expr": "sum by(pod) (container_sockets{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",image!=\"\",container!~\"POD|\"})",
       "legendFormat": "Sockets - {{ pod }}"
      }
     ]
    },
    {
     "title": "CPU Throttling - $pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 291 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (pod) ((container_cpu_cfs_throttled_periods_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"} / container_cpu_cfs_periods_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"}) * 100)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Memory usage - $pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 298 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",image!=\"\",container!~\"POD|\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Network I/O (1m avg) - $pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 305 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_network_receive_bytes_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) * 8",
       "legendFormat": "-> {{ pod }}"
      },
      {
       "expr": "- sum by(pod) (rate(container_network_transmit_bytes_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) * 8",
       "legendFormat": "<- {{ pod }}"
      }
     ]
    },
    {
     "title": "Disk Read/Writes - $pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 312 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m]))",
       "legendFormat": "Reads {{ pod }}"
      },
      {
       "expr": "sum by(pod) (rate(container_fs_writes_bytes_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m]))",
       "legendFormat": "Writes {{ pod }}"
      }
     ]
    },
    {
     "title": "Restarts - $pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 319 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kube_pod_container_status_restarts_total{node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  }
 ]
}